"""Data models for Job Tracking, Token Usage, and Cost Telemetry."""
from datetime import datetime, timezone
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field

class TokenUsageDetails(BaseModel):
    input_text_tokens: int = Field(default=0, description="Tokens from the input article text")
    audio_output_tokens: int = Field(default=0, description="Tokens representing the synthesized audio stream")
    judge_input_tokens: int = Field(default=0, description="Tokens sent to the Multimodal Judge (text + audio)")
    judge_output_tokens: int = Field(default=0, description="Tokens generated by the Multimodal Judge")
    total_tokens: int = Field(default=0, description="Aggregate token count for the pipeline run")

class CostBreakdown(BaseModel):
    tts_cost_usd: float = Field(default=0.0, description="Estimated USD cost for Gemini TTS generation")
    judge_cost_usd: float = Field(default=0.0, description="Estimated USD cost for Gemini Multimodal Judge")
    total_cost_usd: float = Field(default=0.0, description="Total estimated pipeline cost in USD")
    currency: str = Field(default="USD", description="Billing currency")

class JobRecord(BaseModel):
    job_id: str = Field(..., description="Unique job identifier, e.g. job_757eac1a")
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat(), description="ISO timestamp")
    persona: str = Field(..., description="Financial voice persona name")
    audience: str = Field(..., description="Target audience (External Customers, Internal Employees, Both)")
    voice_name: str = Field(..., description="Voice name used (e.g. Sulafat, Charon)")
    article_title: str = Field(default="Financial Guidance Article", description="Title or excerpt headline")
    transcript: str = Field(..., description="Full text transcript sent to the speech model")
    word_count: int = Field(..., description="Transcript word count")
    char_count: int = Field(..., description="Transcript character count")
    
    # Storage & Audio
    gcs_uri: str = Field(..., description="GCS object URI, e.g. gs://bucket/prefix/job_id.mp3")
    signed_url: Optional[str] = Field(default=None, description="Temporary signed or direct playback URL")
    audio_format: str = Field(default="MP3 24kHz @ 320kbps", description="Encoding format")
    duration_seconds: float = Field(default=0.0, description="Duration of generated audio in seconds")
    synthesis_latency_sec: float = Field(default=0.0, description="Time taken to generate speech")
    status: str = Field(default="COMPLETED", description="Job status: COMPLETED, FAILED, RUNNING")
    
    # Token & Cost Telemetry
    token_usage: TokenUsageDetails = Field(default_factory=TokenUsageDetails)
    cost: CostBreakdown = Field(default_factory=CostBreakdown)
    
    # Multimodal Quality Evaluation
    overall_score: Optional[float] = Field(default=None, description="Quality score from 1.0 to 5.0")
    overall_reasoning: Optional[str] = Field(default=None, description="Comprehensive summary explanation for overall score")
    passed_rubric: Optional[bool] = Field(default=None, description="Whether the audio passed the quality gate")
    rubric_metrics: Optional[Dict[str, Any]] = Field(default=None, description="Scores and rationales for 6 rubric dimensions")
    actionable_feedback: Optional[List[str]] = Field(default=None, description="Recommendations from the judge")
    judge_model: Optional[str] = Field(default=None, description="Model used for judging")
    judge_latency_sec: Optional[float] = Field(default=None, description="Evaluation time in seconds")
    error_message: Optional[str] = Field(default=None, description="Error message or diagnostic details if job failed")
    
    # Customization & Progress Telemetry
    voice_customization: Optional[str] = Field(default=None, description="Custom director notes or vocal delivery directives")
    progress_stage: Optional[str] = Field(default=None, description="Active pipeline stage (e.g. CHUNKING, SYNTHESIZING, STITCHING, UPLOADING, EVALUATING, COMPLETED)")
    progress_message: Optional[str] = Field(default=None, description="Human-readable live progress description")
    current_turn: Optional[int] = Field(default=None, description="Active turn index being processed")
    total_turns: Optional[int] = Field(default=None, description="Total turns count for the article")
